name: Sellio
version: '3.8'
services:

  db:
    image: postgres:15-alpine
    container_name: sellio-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U sellio_user -d sellio_db" ]
        interval: 5s
        timeout: 5s
        retries: 5

  app:
    build:
      context: .
    container_name: sellio-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DB_PASSWORD}
      storage.key: ${STORAGE_KEY}
      storage.secret: ${STORAGE_SECRET}
      storage.endpoint: http://localhost:4566
      storage.bucket: ${STORAGE_BUCKET}
      storage.cdn-endpoint: http://localhost:4566
      jwt.secret: ${JWT_SECRET}
      otp.service.url: ${OTP_SERVICE_URL}


      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_ENABLED: false
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: false
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
